version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "atenea-scrapy-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f1skily9e46"
s3_prefix = "atenea-scrapy-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LambdaExecutorFunction=499154085319.dkr.ecr.us-east-1.amazonaws.com/atenea-scrapy"]
